spring.application.name=ai-chatbot-backend

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/aichatbot
spring.datasource.username=root
spring.datasource.password=Devang@8877

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080